// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-pCgGPziHOzeOLzs9abxSX-8Khoa4WE',
    appId: '1:463297718609:web:0967b7ace8799baafd8b70',
    messagingSenderId: '463297718609',
    projectId: 'medicine-manager-d577c',
    authDomain: 'medicine-manager-d577c.firebaseapp.com',
    storageBucket: 'medicine-manager-d577c.firebasestorage.app',
    measurementId: 'G-H7HBQY42M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAqiCyqjDAzDYeoXa7qWZdFUxllGytZFk',
    appId: '1:463297718609:android:7d2c05755ed4d2eefd8b70',
    messagingSenderId: '463297718609',
    projectId: 'medicine-manager-d577c',
    storageBucket: 'medicine-manager-d577c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01M73krqS7tjP8ew7u1pGmxImJmZ99Ww',
    appId: '1:463297718609:ios:c95c4524d88e8de7fd8b70',
    messagingSenderId: '463297718609',
    projectId: 'medicine-manager-d577c',
    storageBucket: 'medicine-manager-d577c.firebasestorage.app',
    iosBundleId: 'com.example.medsManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA01M73krqS7tjP8ew7u1pGmxImJmZ99Ww',
    appId: '1:463297718609:ios:c95c4524d88e8de7fd8b70',
    messagingSenderId: '463297718609',
    projectId: 'medicine-manager-d577c',
    storageBucket: 'medicine-manager-d577c.firebasestorage.app',
    iosBundleId: 'com.example.medsManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6-pCgGPziHOzeOLzs9abxSX-8Khoa4WE',
    appId: '1:463297718609:web:73c33adbd2425336fd8b70',
    messagingSenderId: '463297718609',
    projectId: 'medicine-manager-d577c',
    authDomain: 'medicine-manager-d577c.firebaseapp.com',
    storageBucket: 'medicine-manager-d577c.firebasestorage.app',
    measurementId: 'G-9WGC2VKN1G',
  );
}
